# Generated by Django 5.0.3 on 2024-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='game',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
