# Generated by Django 5.0.3 on 2024-04-03 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_subevent_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='main_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.mainevent'),
        ),
    ]
