# Generated by Django 5.0.3 on 2024-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_subevent_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='image',
            field=models.ImageField(null=True, upload_to='sub_event_images'),
        ),
    ]
