# Generated by Django 5.0.3 on 2024-04-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_subevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='college',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
