# Generated by Django 5.0.3 on 2024-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_college_user_name_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusty',
            field=models.BooleanField(default=False),
        ),
    ]
